GERO-217 - ERBB2 G776_V777 insertions AttributeError - check range_start is None in positions_overlap Prevent AttributeError: 'NoneType' object has no attribute 'get' errors for ERBB2:p.G776_V777insC, ERBB2:p.G776_V777insVGC and ERBB2:p.G776_V777insYVMA